/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.bleedplayer.ui;

import com.mycompany.bleedplayer.model.Playlist;
import com.mycompany.bleedplayer.model.NodoCancion;
import com.mycompany.bleedplayer.audio.*;
import com.mycompany.audio.MetadataReader;
import javax.swing.DefaultListModel;
import javax.swing.ImageIcon;
import java.awt.Image;
import javax.swing.JFileChooser;
import java.io.File;
import com.mpatric.mp3agic.*;

/**
 *
 * @author jv134
 */


public class PlayerUI extends javax.swing.JFrame {
    Playlist playlist = new Playlist();
    Reproductor reproductor = new Reproductor();
    DefaultListModel<String> modeloLista = new DefaultListModel<>();

NodoCancion actual = null;
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(PlayerUI.class.getName());

    /**
     * Creates new form PlayerUI
     */
    public PlayerUI() {
        initComponents();
    listaCanciones.setModel(modeloLista);
     lblPortada.setPreferredSize(new java.awt.Dimension(250, 250));
    lblPortada.setMinimumSize(new java.awt.Dimension(250, 250));
    lblPortada.setMaximumSize(new java.awt.Dimension(250, 250));
    lblPortada.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    lblPortada.setVerticalAlignment(javax.swing.SwingConstants.CENTER);
    
    // Limpiar campos al inicio (pero dejarlos visibles)
    txtNombre.setText("");
    txtArtista.setText("");
    txtGenero.setText("");
    txtDuracion.setText("");
    txtRuta.setText("");
    txtNombre.setEditable(false);
    txtArtista.setEditable(false);
    txtGenero.setEditable(false);
    txtDuracion.setEditable(false);
    txtRuta.setEditable(false);
    
    lblPortada.setText("");
    jreproduciendo.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        listaCanciones = new javax.swing.JList<>();
        btnAgregar = new javax.swing.JButton();
        btnPlay = new javax.swing.JButton();
        btnNext = new javax.swing.JButton();
        txtNombre = new javax.swing.JTextField();
        txtGenero = new javax.swing.JTextField();
        txtDuracion = new javax.swing.JTextField();
        txtRuta = new javax.swing.JTextField();
        txtArtista = new javax.swing.JTextField();
        jreproduciendo = new javax.swing.JLabel();
        lblPortada = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        listaCanciones.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(listaCanciones);

        btnAgregar.setText("Agregar");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });

        btnPlay.setText("Reproducir");
        btnPlay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlayActionPerformed(evt);
            }
        });

        btnNext.setText("Siguiente");

        txtNombre.setText("Nombre");
        txtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreActionPerformed(evt);
            }
        });

        txtGenero.setText("Genero");

        txtDuracion.setText("Duracion");

        txtRuta.setText("Ruta");
        txtRuta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRutaActionPerformed(evt);
            }
        });

        txtArtista.setText("Artista");

        jreproduciendo.setText("Reproduciendo");

        lblPortada.setText("Portada");
        lblPortada.setMaximumSize(new java.awt.Dimension(250, 250));
        lblPortada.setMinimumSize(new java.awt.Dimension(250, 250));
        lblPortada.setPreferredSize(new java.awt.Dimension(250, 250));

        jLabel1.setFont(new java.awt.Font("Serif", 0, 36)); // NOI18N
        jLabel1.setText("Bleed Player");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtNombre, javax.swing.GroupLayout.DEFAULT_SIZE, 98, Short.MAX_VALUE)
                            .addComponent(txtArtista)
                            .addComponent(txtGenero)
                            .addComponent(txtDuracion)
                            .addComponent(txtRuta)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnAgregar)
                            .addComponent(btnPlay)
                            .addComponent(btnNext))))
                .addGap(86, 86, 86)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jreproduciendo)
                    .addComponent(lblPortada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(260, 260, 260))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(72, 72, 72)
                .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtArtista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtGenero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtDuracion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtRuta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(63, 63, 63))
            .addGroup(layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAgregar)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnPlay)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnNext))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblPortada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37)
                        .addComponent(jreproduciendo)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
                                        
     JFileChooser fileChooser = new JFileChooser();
    fileChooser.setFileFilter(new javax.swing.filechooser.FileNameExtensionFilter(
        "Archivos MP3", "mp3"));
    
    int result = fileChooser.showOpenDialog(this);
    
    if(result == JFileChooser.APPROVE_OPTION){
        File archivo = fileChooser.getSelectedFile();
        String ruta = archivo.getAbsolutePath();
        
        // Leer metadatos del archivo
        String nombre = archivo.getName().replace(".mp3", "");
        String artista = "Messhugah";
        String genero = "Metal Progresivo";
        String duracion = "7:22";
        
        try {
            Mp3File mp3 = new Mp3File(ruta);
            if(mp3.hasId3v2Tag()){
                ID3v2 tag = mp3.getId3v2Tag();
                if(tag.getArtist() != null) artista = tag.getArtist();
                if(tag.getGenreDescription() != null) genero = tag.getGenreDescription();
                if(tag.getTitle() != null) nombre = tag.getTitle();
                
                long segundos = mp3.getLengthInSeconds();
                duracion = String.format("%d:%02d", segundos/60, segundos%60);
            }
        } catch(Exception e){
            System.out.println("Error al leer metadatos: " + e.getMessage());
        }
        
        // Agregar a la playlist
        playlist.agregarCancion(nombre, artista, genero, duracion, ruta);
        
        // Actualizar la lista visual
        modeloLista.addElement(nombre);
        
        // Actualizar campos de texto
        txtNombre.setText(nombre);
        txtArtista.setText(artista);
        txtGenero.setText(genero);
        txtDuracion.setText(duracion);
        txtRuta.setText(ruta);
        
        System.out.println("Cancion agregada: " + nombre);
    }
   

        // TODO add your handling code here:
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed
    txtNombre.setEditable(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreActionPerformed

    private void btnPlayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlayActionPerformed
  String nombre = listaCanciones.getSelectedValue();
    
    if(nombre == null){
        System.out.println("No hay cancion seleccionada");
        return;
    }
    
    actual = playlist.buscar(nombre);
    
    if(actual != null){
        System.out.println("Reproduciendo: " + actual.nombre);
        System.out.println("Ruta: " + actual.rutaArchivo);
        
        // Actualizar campos de texto con los datos de la canción
        txtNombre.setText(actual.nombre);
        txtArtista.setText(actual.artista);
        txtGenero.setText(actual.genero);
        txtDuracion.setText(actual.duracion);
        txtRuta.setText(actual.rutaArchivo);
        
        jreproduciendo.setText("Reproduciendo: " + actual.nombre);
        
        // REPRODUCIR AUDIO
        reproductor.reproducir(actual.rutaArchivo);
        
        // MOSTRAR PORTADA
        ImageIcon portada = MetadataReader.obtenerPortada(actual.rutaArchivo);
        
        if(portada == null){
            System.out.println("No hay portada en el MP3, cargando portada predeterminada...");
            try {
                portada = new ImageIcon("C:\\Users\\jv134\\OneDrive\\Escritorio\\CUAltos\\4to semestre\\Estructura de datos\\BleedPlayer\\src\\main\\java\\resources\\bleed.jpg");
                
                if(portada.getImageLoadStatus() == java.awt.MediaTracker.COMPLETE){
                    System.out.println("Portada predeterminada cargada correctamente");
                } else {
                    System.out.println("Error: la imagen no se cargo correctamente");
                    portada = null;
                }
            } catch(Exception e){
                System.out.println("Error al cargar portada predeterminada: " + e.getMessage());
                e.printStackTrace();
            }
        } else {
            System.out.println("Portada encontrada en el archivo MP3");
        }
        
        if(portada != null){
            Image img = portada.getImage().getScaledInstance(
                250, 250, Image.SCALE_SMOOTH);
            lblPortada.setIcon(new ImageIcon(img));
            lblPortada.setText("");
        } else {
            lblPortada.setIcon(null);
            lblPortada.setText("Sin portada");
        }
    } else {
        System.out.println("No se encontró la canción en la playlist");
    }
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPlayActionPerformed

    private void txtRutaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRutaActionPerformed
 
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRutaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new PlayerUI().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnNext;
    private javax.swing.JButton btnPlay;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel jreproduciendo;
    private javax.swing.JLabel lblPortada;
    private javax.swing.JList<String> listaCanciones;
    private javax.swing.JTextField txtArtista;
    private javax.swing.JTextField txtDuracion;
    private javax.swing.JTextField txtGenero;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtRuta;
    // End of variables declaration//GEN-END:variables
}
